name: Validate project

on:
  pull_request:
    branches: [ main ]
jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - uses: hashicorp/setup-terraform@v2
        with:
            terraform_version: "1.7.5"
            terraform_wrapper: true     
      - name: Terraform format
        run: terraform fmt -check -recursive
      - name: Terraform init
        run: |
            terraform init \
                -input=false \
                -backend-config="bucket=jf-terraform-state-ts" \
                -backend-config="key=infra.tfstate" \
                -backend-config="region=us-east-1" \
                -backend-config="encrypt=true"
      - name: Terraform validate
        run: terraform validate
          
     